-- In ~/.config/nvim/lua/plugins/dap.lua
-- Generated by claude
return {
  {
    "mfussenegger/nvim-dap",
    dependencies = {
      "rcarriga/nvim-dap-ui",
      "theHamsta/nvim-dap-virtual-text",
      "nvim-neotest/nvim-nio",
    },
    config = function()
      local dap = require("dap")

      -- Configure for C/C++ with LLDB
      dap.adapters.lldb = {
        type = "executable",
        command = "/usr/bin/lldb-vscode", -- or lldb-dap
        name = "lldb",
      }

      dap.configurations.c = {
        {
          name = "Launch",
          type = "lldb",
          request = "launch",
          program = function()
            return vim.fn.input("Path to executable: ", vim.fn.getcwd() .. "/", "file")
          end,
          cwd = "${workspaceFolder}",
          stopOnEntry = false,
          args = {},
        },
      }

      -- UI setup
      require("dapui").setup()
      require("nvim-dap-virtual-text").setup()
    end,
    keys = {
      { "<leader>db", "<cmd>DapToggleBreakpoint<cr>", desc = "Toggle Breakpoint" },
      { "<leader>dc", "<cmd>DapContinue<cr>", desc = "Continue" },
      { "<leader>ds", "<cmd>DapStepOver<cr>", desc = "Step Over" },
      { "<leader>di", "<cmd>DapStepInto<cr>", desc = "Step Into" },
      { "<leader>do", "<cmd>DapStepOut<cr>", desc = "Step Out" },
      { "<leader>du", "<cmd>lua require('dapui').toggle()<cr>", desc = "Toggle UI" },
    },
  },
}
